/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffeesystem;

import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.*;
import javax.swing.border.*;


public class Account extends javax.swing.JFrame {

    // Create a border for text fields
    Border rounded = new LineBorder(new Color(102, 102, 102), 1, true);
    Border empty = new EmptyBorder(0, 10, 0, 0);
    Border border = new CompoundBorder(rounded, empty);
    
    public Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtnGrp = new javax.swing.ButtonGroup();
        logoutBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ourMenuBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        orderListBtn = new javax.swing.JButton();
        userListBtn = new javax.swing.JButton();
        ourMenuBtn1 = new javax.swing.JButton();
        myProfileScrollpane = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newFNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newEmailField = new javax.swing.JTextField();
        newContactField = new javax.swing.JTextField();
        maleRB = new javax.swing.JRadioButton();
        femaleRB = new javax.swing.JRadioButton();
        otherRB = new javax.swing.JRadioButton();
        saveProfileChange = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        newLNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        oldPassField = new javax.swing.JPasswordField();
        newPassField = new javax.swing.JPasswordField();
        confirmPassField = new javax.swing.JPasswordField();
        changePassBtn = new javax.swing.JButton();

        if(CoffeeSystem.userGender == null){
            genderBtnGrp.clearSelection();
        }
        else if(CoffeeSystem.userGender.equalsIgnoreCase("male")){
            maleRB.setSelected(true);
        }
        else if(CoffeeSystem.userGender.equalsIgnoreCase("female")){
            femaleRB.setSelected(true);
        }
        else if(CoffeeSystem.userGender.equalsIgnoreCase("other")){
            otherRB.setSelected(true);
        }

        logoutBtn.setBackground(new java.awt.Color(232, 231, 230));
        logoutBtn.setFont(new java.awt.Font("Leelawadee UI", 2, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(113, 96, 64));
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        logoutBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Profile");
        setResizable(false);

        mainPanel.setPreferredSize(new java.awt.Dimension(1280, 900));

        jPanel3.setBackground(new java.awt.Color(232, 231, 230));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 900));

        ourMenuBtn.setBackground(new java.awt.Color(232, 231, 230));
        ourMenuBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ourMenuBtn.setForeground(new java.awt.Color(113, 96, 64));
        ourMenuBtn.setText("Our Menu");
        ourMenuBtn.setBorder(null);
        ourMenuBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ourMenuBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        ourMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourMenuBtnActionPerformed(evt);
            }
        });

        productBtn.setBackground(new java.awt.Color(232, 231, 230));
        productBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        productBtn.setForeground(new java.awt.Color(113, 96, 64));
        productBtn.setText("Products");
        productBtn.setBorder(null);
        productBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        productBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });

        profileBtn.setBackground(new java.awt.Color(230, 230, 230));
        profileBtn.setFont(new java.awt.Font("Leelawadee UI", 2, 18)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(113, 96, 64));
        profileBtn.setText("My Profile");
        profileBtn.setBorder(null);
        profileBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        profileBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        jSeparator1.setPreferredSize(new java.awt.Dimension(300, 10));

        orderListBtn.setBackground(new java.awt.Color(230, 230, 230));
        orderListBtn.setFont(new java.awt.Font("Leelawadee UI", 3, 18)); // NOI18N
        orderListBtn.setForeground(new java.awt.Color(113, 96, 64));
        orderListBtn.setText("Orders");
        orderListBtn.setBorder(null);
        orderListBtn.setFocusable(false);
        orderListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        orderListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        orderListBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        orderListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderListBtnActionPerformed(evt);
            }
        });

        userListBtn.setBackground(new java.awt.Color(230, 230, 230));
        userListBtn.setFont(new java.awt.Font("Leelawadee UI", 3, 18)); // NOI18N
        userListBtn.setForeground(new java.awt.Color(113, 96, 64));
        userListBtn.setText("Users");
        userListBtn.setBorder(null);
        userListBtn.setFocusable(false);
        userListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        userListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        userListBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        userListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userListBtnActionPerformed(evt);
            }
        });

        ourMenuBtn1.setBackground(new java.awt.Color(232, 231, 230));
        ourMenuBtn1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ourMenuBtn1.setForeground(new java.awt.Color(113, 96, 64));
        ourMenuBtn1.setText("Dashboard");
        ourMenuBtn1.setBorder(null);
        ourMenuBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ourMenuBtn1.setPreferredSize(new java.awt.Dimension(170, 40));
        ourMenuBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourMenuBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ourMenuBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(orderListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ourMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(ourMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(ourMenuBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(orderListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(userListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        myProfileScrollpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        myProfileScrollpane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel4.setBackground(new java.awt.Color(249, 244, 239));
        jPanel4.setPreferredSize(new java.awt.Dimension(1020, 850));
        jPanel4.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 8, 38));
        jLabel1.setText("My profile");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 50));
        jLabel1.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 8, 38));
        jLabel2.setText("First Name:");

        newFNameField.setBackground(new java.awt.Color(217, 217, 217));
        newFNameField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        newFNameField.setForeground(new java.awt.Color(71, 54, 47));
        newFNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        newFNameField.setCaretColor(new java.awt.Color(71, 54, 47));
        newFNameField.setPreferredSize(new java.awt.Dimension(350, 40));
        newFNameField.setSelectedTextColor(new java.awt.Color(59, 44, 39));
        newFNameField.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 8, 38));
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 8, 38));
        jLabel4.setText("Contact:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 8, 38));
        jLabel5.setText("Gender:");

        newEmailField.setBackground(new java.awt.Color(217, 217, 217));
        newEmailField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        newEmailField.setForeground(new java.awt.Color(71, 54, 47));
        newEmailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        newEmailField.setCaretColor(new java.awt.Color(71, 54, 47));
        newEmailField.setPreferredSize(new java.awt.Dimension(795, 40));
        newEmailField.setSelectedTextColor(new java.awt.Color(59, 44, 39));
        newEmailField.setSelectionColor(new java.awt.Color(255, 255, 255));

        newContactField.setBackground(new java.awt.Color(217, 217, 217));
        newContactField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        newContactField.setForeground(new java.awt.Color(71, 54, 47));
        newContactField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        newContactField.setCaretColor(new java.awt.Color(71, 54, 47));
        newContactField.setPreferredSize(new java.awt.Dimension(795, 40));
        newContactField.setSelectedTextColor(new java.awt.Color(59, 44, 39));
        newContactField.setSelectionColor(new java.awt.Color(255, 255, 255));
        newContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newContactFieldActionPerformed(evt);
            }
        });

        maleRB.setBackground(new java.awt.Color(249, 244, 239));
        genderBtnGrp.add(maleRB);
        maleRB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        maleRB.setForeground(new java.awt.Color(71, 54, 47));
        maleRB.setText("Male");
        maleRB.setPreferredSize(new java.awt.Dimension(100, 25));
        maleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRBActionPerformed(evt);
            }
        });

        femaleRB.setBackground(new java.awt.Color(249, 244, 239));
        genderBtnGrp.add(femaleRB);
        femaleRB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        femaleRB.setForeground(new java.awt.Color(71, 54, 47));
        femaleRB.setText("Female");
        femaleRB.setPreferredSize(new java.awt.Dimension(100, 25));

        otherRB.setBackground(new java.awt.Color(249, 244, 239));
        genderBtnGrp.add(otherRB);
        otherRB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        otherRB.setForeground(new java.awt.Color(71, 54, 47));
        otherRB.setText("Other");
        otherRB.setPreferredSize(new java.awt.Dimension(100, 25));

        saveProfileChange.setBackground(new java.awt.Color(140, 120, 81));
        saveProfileChange.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        saveProfileChange.setForeground(new java.awt.Color(255, 255, 254));
        saveProfileChange.setText("Save");
        saveProfileChange.setBorder(null);
        saveProfileChange.setPreferredSize(new java.awt.Dimension(100, 50));
        saveProfileChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProfileChangeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 8, 38));
        jLabel7.setText("Last Name:");

        newLNameField.setBackground(new java.awt.Color(217, 217, 217));
        newLNameField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        newLNameField.setForeground(new java.awt.Color(71, 54, 47));
        newLNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        newLNameField.setCaretColor(new java.awt.Color(71, 54, 47));
        newLNameField.setPreferredSize(new java.awt.Dimension(350, 40));
        newLNameField.setSelectedTextColor(new java.awt.Color(59, 44, 39));
        newLNameField.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 3, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 8, 38));
        jLabel6.setText("Change Password");
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 8, 38));
        jLabel8.setText("Old Password:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 8, 38));
        jLabel9.setText("New Password:");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 8, 38));
        jLabel10.setText("Confirm Password:");

        oldPassField.setBackground(new java.awt.Color(217, 217, 217));
        oldPassField.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        oldPassField.setForeground(new java.awt.Color(71, 54, 47));
        oldPassField.setText("Placeholder");
        oldPassField.setPreferredSize(new java.awt.Dimension(795, 40));

        newPassField.setBackground(new java.awt.Color(217, 217, 217));
        newPassField.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        newPassField.setForeground(new java.awt.Color(71, 54, 47));
        newPassField.setPreferredSize(new java.awt.Dimension(795, 40));
        newPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassFieldActionPerformed(evt);
            }
        });

        confirmPassField.setBackground(new java.awt.Color(217, 217, 217));
        confirmPassField.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        confirmPassField.setForeground(new java.awt.Color(71, 54, 47));
        confirmPassField.setPreferredSize(new java.awt.Dimension(795, 40));
        confirmPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassFieldActionPerformed(evt);
            }
        });

        changePassBtn.setBackground(new java.awt.Color(140, 120, 81));
        changePassBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        changePassBtn.setForeground(new java.awt.Color(255, 255, 254));
        changePassBtn.setText("Change Password");
        changePassBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        changePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(206, 206, 206))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(80, 80, 80))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(126, 126, 126)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(newFNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(newLNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(newEmailField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(maleRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(femaleRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(otherRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(saveProfileChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oldPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newFNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(newLNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newContactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femaleRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addComponent(saveProfileChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(oldPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(changePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        if(CoffeeSystem.userGender == null || CoffeeSystem.userGender.equals("Male")){
            ImageIcon image = new ImageIcon(getClass().getResource("/images/male-icon.png"));

            jLabel1.setIcon(image);
            jLabel1.setText(" My Profile");
        }
        else{
            ImageIcon image = new ImageIcon(getClass().getResource("/images/female-icon.png"));

            jLabel1.setIcon(image);
            jLabel1.setText(" My Profile");
        }
        newFNameField.setBorder(border);
        newFNameField.setText(CoffeeSystem.userFName);
        newEmailField.setBorder(border);
        newEmailField.setText(CoffeeSystem.userEmail);
        newContactField.setBorder(border);
        newContactField.setText(CoffeeSystem.userContact);
        maleRB.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent e){
            }
        });
        femaleRB.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent e){
            }
        });
        otherRB.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent e){
            }
        });
        newLNameField.setBorder(border);
        newLNameField.setText(CoffeeSystem.userLName);
        oldPassField.setBorder(border);
        newPassField.setBorder(border);
        confirmPassField.setBorder(border);

        myProfileScrollpane.setViewportView(jPanel4);
        myProfileScrollpane.getVerticalScrollBar().setUnitIncrement(20);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myProfileScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myProfileScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        myProfileScrollpane.getVerticalScrollBar().setUnitIncrement(20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int confirmLogout = JOptionPane.showConfirmDialog(null, "Do you want to logout?", "Log Out", JOptionPane.YES_NO_OPTION);

        if (confirmLogout == JOptionPane.YES_NO_OPTION){
            LogIn LogInFrame = new LogIn();
            LogInFrame.setVisible(true);
            LogInFrame.pack();
            LogInFrame.setLocationRelativeTo(null);

            this.dispose();
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void ourMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ourMenuBtnActionPerformed
        // TODO add your handling code here:
        Menu menuFrame = new Menu();
        menuFrame.setVisible(true);
        menuFrame.pack();
        menuFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_ourMenuBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:        
            ProductPage productFrame = new ProductPage();
            productFrame.setVisible(true);
            productFrame.pack();
            productFrame.setLocationRelativeTo(null);

            this.dispose();
        
    }//GEN-LAST:event_productBtnActionPerformed

    private void maleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRBActionPerformed

    private void saveProfileChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProfileChangeActionPerformed
        // TODO add your handling code here:
        
        String newFName = newFNameField.getText();
        String newLName = newLNameField.getText();
        String newEmail = newEmailField.getText();
        String newContact = newContactField.getText();
        
        if (newFNameField.getText().isEmpty() || newEmailField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Don't leave your first name and email empty");
        }
        else if(!(newFName.equals(CoffeeSystem.userFName) && newLName.equals(CoffeeSystem.userLName) && newEmail.equals(CoffeeSystem.userEmail))){
            DBQuery.updateUserInfo();
        }
        else if(newContactField.getText().isEmpty() && CoffeeSystem.userContact != null){
            DBQuery.updateUserInfo();
        }
        else if(!newContactField.getText().isEmpty() && !(newContact.equals(CoffeeSystem.userContact))){
            DBQuery.updateUserInfo();
        }
        else if(!(methods.getSelectedButton(genderBtnGrp) == null) && CoffeeSystem.userGender == null){
            DBQuery.updateUserInfo();
        }
        else if(!(methods.getSelectedButton(genderBtnGrp) == null) && !methods.getSelectedButton(genderBtnGrp).equals(CoffeeSystem.userGender)){
            DBQuery.updateUserInfo();
        }
        else{
            JOptionPane.showMessageDialog(null, "Can't save\nNothing is changed");
        }
        
        if(CoffeeSystem.userGender == null || CoffeeSystem.userGender.equals("Male")){
            ImageIcon image = new ImageIcon(getClass().getResource("/images/male-icon.png"));

            jLabel1.setIcon(image);
            jLabel1.setText(" My Profile");
        }
        else{
            ImageIcon image = new ImageIcon(getClass().getResource("/images/female-icon.png"));

            jLabel1.setIcon(image);
            jLabel1.setText(" My Profile");
        }
    }//GEN-LAST:event_saveProfileChangeActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileBtnActionPerformed

    private void newContactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newContactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newContactFieldActionPerformed

    private void confirmPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassFieldActionPerformed

    private void changePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassBtnActionPerformed
        // TODO add your handling code here:
        
        if(oldPassField.getText().isEmpty() || newPassField.getText().isEmpty() || confirmPassField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all the fields to continue");
            
            oldPassField.setText("placeholder");
            newPassField.setText("");
            confirmPassField.setText("");
        }
        else if(!CoffeeSystem.hashedPassword.equals(methods.passwordHashing(oldPassField.getText()))){
            JOptionPane.showMessageDialog(null, "Incorrect old password\nTry again");
            
            oldPassField.setText("placeholder");
            newPassField.setText("");
            confirmPassField.setText("");
        }
        else if(CoffeeSystem.hashedPassword.equals(methods.passwordHashing(newPassField.getText()))){
            JOptionPane.showMessageDialog(null, "New password must be different from your old password");
            
            oldPassField.setText("placeholder");
            newPassField.setText("");
            confirmPassField.setText("");
        }
        else{
            if( newPassField.getText().equals(confirmPassField.getText())){
                String newHashedPass = methods.passwordHashing(newPassField.getText());

                DBQuery.updatePassword(newHashedPass, CoffeeSystem.userEmail);
                
                oldPassField.setText("placeholder");
                newPassField.setText("");
                confirmPassField.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null, "New password don't match\nTry again");
            }
        }
    }//GEN-LAST:event_changePassBtnActionPerformed

    private void orderListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderListBtnActionPerformed
        // TODO add your handling code here:
        OrderPage orderPageFrame = new OrderPage();
        orderPageFrame.setVisible(true);
        orderPageFrame.pack();
        orderPageFrame.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_orderListBtnActionPerformed

    private void userListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userListBtnActionPerformed
        // TODO add your handling code here:
        UserPage userFrame = new UserPage();
        userFrame.setVisible(true);
        userFrame.pack();
        userFrame.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_userListBtnActionPerformed

    private void newPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassFieldActionPerformed

    private void ourMenuBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ourMenuBtn1ActionPerformed
        // TODO add your handling code here:
        Menu menuFrame = new Menu();
        menuFrame.setVisible(true);
        menuFrame.pack();
        menuFrame.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_ourMenuBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePassBtn;
    private javax.swing.JPasswordField confirmPassField;
    public static javax.swing.JRadioButton femaleRB;
    public static javax.swing.ButtonGroup genderBtnGrp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    public static javax.swing.JRadioButton maleRB;
    private javax.swing.JScrollPane myProfileScrollpane;
    public static javax.swing.JTextField newContactField;
    public static javax.swing.JTextField newEmailField;
    public static javax.swing.JTextField newFNameField;
    public static javax.swing.JTextField newLNameField;
    private javax.swing.JPasswordField newPassField;
    private javax.swing.JPasswordField oldPassField;
    public static javax.swing.JButton orderListBtn;
    public static javax.swing.JRadioButton otherRB;
    public static javax.swing.JButton ourMenuBtn;
    public static javax.swing.JButton ourMenuBtn1;
    public static javax.swing.JButton productBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton saveProfileChange;
    public static javax.swing.JButton userListBtn;
    // End of variables declaration//GEN-END:variables
}
