/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffeesystem;

import static coffeesystem.Dashboard.salesTable;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author johnc
 */
public class OrderPage extends javax.swing.JFrame {

    /**
     * Creates new form OrderPage
     */
    public OrderPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        profileBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        ourMenuBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        orderListBtn = new javax.swing.JButton();
        userListBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchBarField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        searchByCB = new javax.swing.JComboBox<>();
        sortingCB = new javax.swing.JComboBox<>();
        clearRecordBtn = new javax.swing.JButton();
        removeRecordBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 244, 239));

        jPanel2.setBackground(new java.awt.Color(230, 230, 230));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 720));

        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 10));

        profileBtn.setBackground(new java.awt.Color(230, 230, 230));
        profileBtn.setFont(new java.awt.Font("Leelawadee UI", 2, 18)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(113, 96, 64));
        profileBtn.setText("My Profile");
        profileBtn.setBorder(null);
        profileBtn.setFocusable(false);
        profileBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        profileBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(230, 230, 230));
        logoutBtn.setFont(new java.awt.Font("Leelawadee UI", 2, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(113, 96, 64));
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setFocusable(false);
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        logoutBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        dashboardBtn.setBackground(new java.awt.Color(232, 231, 230));
        dashboardBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(113, 96, 64));
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setBorder(null);
        dashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        dashboardBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });

        ourMenuBtn.setBackground(new java.awt.Color(232, 231, 230));
        ourMenuBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ourMenuBtn.setForeground(new java.awt.Color(113, 96, 64));
        ourMenuBtn.setText("Our Menu");
        ourMenuBtn.setBorder(null);
        ourMenuBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ourMenuBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        ourMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourMenuBtnActionPerformed(evt);
            }
        });

        productBtn.setBackground(new java.awt.Color(232, 231, 230));
        productBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        productBtn.setForeground(new java.awt.Color(113, 96, 64));
        productBtn.setText("Products");
        productBtn.setBorder(null);
        productBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        productBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });

        orderListBtn.setBackground(new java.awt.Color(230, 230, 230));
        orderListBtn.setFont(new java.awt.Font("Leelawadee UI", 3, 18)); // NOI18N
        orderListBtn.setForeground(new java.awt.Color(113, 96, 64));
        orderListBtn.setText("Orders");
        orderListBtn.setBorder(null);
        orderListBtn.setFocusable(false);
        orderListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        orderListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        orderListBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        orderListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderListBtnActionPerformed(evt);
            }
        });

        userListBtn.setBackground(new java.awt.Color(230, 230, 230));
        userListBtn.setFont(new java.awt.Font("Leelawadee UI", 3, 18)); // NOI18N
        userListBtn.setForeground(new java.awt.Color(113, 96, 64));
        userListBtn.setText("Users");
        userListBtn.setBorder(null);
        userListBtn.setFocusable(false);
        userListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        userListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        userListBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        userListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userListBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(orderListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ourMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(ourMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(orderListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(userListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        orderTable.setBackground(new java.awt.Color(240, 240, 240));
        orderTable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html>Order<br>No</html>", "Beverages", "Qnty", "Price", "Customer ID", "<html>Payment<br>Method</html>", "<html>Service<br>Option</html>", "Delivery Address", "Order Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        });
        orderTable.setRowHeight(30);
        orderTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        JTableHeader header = orderTable.getTableHeader();

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) orderTable.getDefaultRenderer(Object.class);
        renderer.setHorizontalAlignment( SwingConstants.CENTER );
        renderer.setVerticalAlignment( SwingConstants.CENTER );

        Dimension d = header.getPreferredSize();
        header.setPreferredSize(new Dimension(d.width, 50));
        header.setFont(new java.awt.Font("SansSerif", 1, 12));
        header.setBackground(new java.awt.Color(240,240,240));

        orderTable.getColumnModel().getColumn(1).setCellRenderer(new methods.TextAreaRenderer());
        orderTable.getColumnModel().getColumn(4).setCellRenderer(new methods.TextAreaRenderer());
        orderTable.getColumnModel().getColumn(7).setCellRenderer(new methods.TextAreaRenderer());

        orderTable.getColumnModel().getColumn(0).setPreferredWidth(40);
        orderTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        orderTable.getColumnModel().getColumn(2).setPreferredWidth(40);
        orderTable.getColumnModel().getColumn(3).setPreferredWidth(80);
        orderTable.getColumnModel().getColumn(4).setPreferredWidth(80);
        orderTable.getColumnModel().getColumn(5).setPreferredWidth(60);
        orderTable.getColumnModel().getColumn(6).setPreferredWidth(80);
        orderTable.getColumnModel().getColumn(7).setPreferredWidth(200);
        jScrollPane1.setViewportView(orderTable);
        DBQuery.loadOrders("orderTB.orderID");

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 8, 38));
        jLabel1.setText("Orders Table");

        searchBarField.setPreferredSize(new java.awt.Dimension(240, 25));

        searchBtn.setBackground(new java.awt.Color(140, 120, 81));
        searchBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 254));
        searchBtn.setText("Search");
        searchBtn.setPreferredSize(new java.awt.Dimension(75, 25));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchByCB.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        searchByCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by Product Name", "Search by Payment Method", "Search by Service Option", "Search by Date" }));
        searchByCB.setMinimumSize(new java.awt.Dimension(120, 25));
        searchByCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCBActionPerformed(evt);
            }
        });

        sortingCB.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        sortingCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by Order No(Asc)", "Sort by Order No(Desc)", "Sort by Product Name(Asc)", "Sort by Product Name(Desc)", "Sort by Quantity(Asc)", "Sort by Quantity(Desc)", "Sort by Price(Asc)", "Sort by Price(Desc)", "Sort by Customer ID(Asc)", "Sort by Customer ID(Desc)" }));
        sortingCB.setFocusable(false);
        sortingCB.setPreferredSize(new java.awt.Dimension(190, 25));
        sortingCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortingCBActionPerformed(evt);
            }
        });

        clearRecordBtn.setBackground(new java.awt.Color(140, 120, 81));
        clearRecordBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        clearRecordBtn.setForeground(new java.awt.Color(255, 255, 254));
        clearRecordBtn.setText("Clear Records");
        clearRecordBtn.setPreferredSize(new java.awt.Dimension(145, 35));
        clearRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearRecordBtnActionPerformed(evt);
            }
        });

        removeRecordBtn.setBackground(new java.awt.Color(140, 120, 81));
        removeRecordBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        removeRecordBtn.setForeground(new java.awt.Color(255, 255, 254));
        removeRecordBtn.setText("Remove Record");
        removeRecordBtn.setPreferredSize(new java.awt.Dimension(145, 35));
        removeRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRecordBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sortingCB, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287)
                        .addComponent(searchBarField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(searchByCB, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(removeRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(clearRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortingCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        Account accountFrame = new Account();
        accountFrame.setVisible(true);
        accountFrame.pack();
        accountFrame.setLocationRelativeTo(null);

        Account.ourMenuBtn.setText("Dashboard");
        Account.productBtn.setText("Products");
        Account.orderListBtn.setVisible(true);
        Account.userListBtn.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_profileBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int confirmLogout = JOptionPane.showConfirmDialog(null, "Do you want to logout?", "Log Out", JOptionPane.YES_NO_OPTION);

        if (confirmLogout == JOptionPane.YES_NO_OPTION){
            LogIn LogInFrame = new LogIn();
            LogInFrame.setVisible(true);
            LogInFrame.pack();
            LogInFrame.setLocationRelativeTo(null);

            this.dispose();
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String[] orderBy =  {"orderTB.orderID ASC", "orderTB.orderID DESC", "Product ASC", "Product DESC", "orderTB.productQnty ASC", "orderTB.productQnty DESC", "orderTB.orderPrice ASC", "orderTB.orderPrice DESC", "orderTB.customerID ASC", "orderTB.customerID DESC"};
        String[] searchBy = {"productTB.productName", "transactionTB.paymentMethod", "transactionTB.serviceOption", "transactionTB.dateOfTransaction"};
        
        methods.clearTable(orderTable.getModel());
        if(searchBarField.getText().isEmpty()){
            DBQuery.loadOrders(orderBy[sortingCB.getSelectedIndex()]);
        }
        else{
            DBQuery.loadOrders(orderBy[sortingCB.getSelectedIndex()], searchBy[searchByCB.getSelectedIndex()],searchBarField.getText());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchByCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByCBActionPerformed

    private void sortingCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortingCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortingCBActionPerformed

    private void removeRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRecordBtnActionPerformed
        // TODO add your handling code here:
        if(!DBQuery.getUserRole(CoffeeSystem.userEmail).equals("admin")){
            JOptionPane.showMessageDialog(null, "Only admin can remove order records");
        }
        else{
            int confirmRemoval = JOptionPane.showConfirmDialog(null, "Are you use want to delete this record?\nRemoving this will delete its record from the database", "Remove record", JOptionPane.YES_NO_OPTION);

            if(confirmRemoval == JOptionPane.YES_OPTION){
                for(int i = 0; i < orderTable.getSelectedRowCount(); i++){
                    int orderID = Integer.parseInt(orderTable.getValueAt(orderTable.getSelectedRow(), 0).toString());

                    DBQuery.removeRecord(orderID);

                    DefaultTableModel dt = (DefaultTableModel) orderTable.getModel();
                    dt.removeRow(orderTable.getSelectedRow());

                    JOptionPane.showMessageDialog(null, "Order has been deleted");
                }
            }
        }
    }//GEN-LAST:event_removeRecordBtnActionPerformed

    private void clearRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearRecordBtnActionPerformed
        // TODO add your handling code here:
        if(!DBQuery.getUserRole(CoffeeSystem.userEmail).equals("admin")){
            JOptionPane.showMessageDialog(null, "Only admin can clear order records");
        }
        else{
            int confirmClearRecord = JOptionPane.showConfirmDialog(null, "Are you use you want to clear order records?\n(Records can be retrieved in your database)", "Clear Records", JOptionPane.YES_NO_OPTION);

            if(confirmClearRecord == JOptionPane.YES_OPTION){
                DBQuery.clearAdminSideOrderTable();
                methods.clearTable(orderTable.getModel());

                JOptionPane.showMessageDialog(null, "Records has been successfully deleted");
            }
        }
    }//GEN-LAST:event_clearRecordBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        Dashboard dashboardFrame = new Dashboard();
        dashboardFrame.setVisible(true);
        dashboardFrame.pack();
        dashboardFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void ourMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ourMenuBtnActionPerformed
        // TODO add your handling code here:
        Menu menuFrame = new Menu();
        menuFrame.setVisible(true);
        menuFrame.pack();
        menuFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_ourMenuBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
        ProductPage productFrame = new ProductPage();
        productFrame.setVisible(true);
        productFrame.pack();
        productFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_productBtnActionPerformed

    private void orderListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderListBtnActionPerformed
        // TODO add your handling code here:
        OrderPage orderPageFrame = new OrderPage();
        orderPageFrame.setVisible(true);
        orderPageFrame.pack();
        orderPageFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_orderListBtnActionPerformed

    private void userListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userListBtnActionPerformed
        // TODO add your handling code here:
        UserPage userFrame = new UserPage();
        userFrame.setVisible(true);
        userFrame.pack();
        userFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_userListBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearRecordBtn;
    public static javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logoutBtn;
    public static javax.swing.JButton orderListBtn;
    public static javax.swing.JTable orderTable;
    public static javax.swing.JButton ourMenuBtn;
    public static javax.swing.JButton productBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton removeRecordBtn;
    private javax.swing.JTextField searchBarField;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> searchByCB;
    public static javax.swing.JComboBox<String> sortingCB;
    public static javax.swing.JButton userListBtn;
    // End of variables declaration//GEN-END:variables
}
