/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffeesystem;

import static coffeesystem.Menu.bagContent;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author johnc
 */
public class Payment extends javax.swing.JFrame {

    private static JFrame mainFrame;
    
    // Create a border for text fields
    Border rounded = new LineBorder(new Color(102, 102, 102), 1, true);
    Border empty = new EmptyBorder(0, 10, 0, 0);
    Border border = new CompoundBorder(rounded, empty);
    
    /**
     * Creates new form Payment
     */
    public Payment(JFrame mainFrame) {
        this.mainFrame = mainFrame;
        
        this.addWindowListener(new WindowAdapter(){
                @Override
                public void windowClosing(WindowEvent e){
                mainFrame.setEnabled(true);
            }
        });
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentButtonGroup = new javax.swing.ButtonGroup();
        deliveryPickupGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receiptTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        gcashRB = new javax.swing.JRadioButton();
        cashRB = new javax.swing.JRadioButton();
        pickupRB = new javax.swing.JRadioButton();
        deliveryRB = new javax.swing.JRadioButton();
        addressTextFLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        cashRB.setSelected(true);

        pickupRB.setSelected(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(530, 770));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 244, 239));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 740));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 8, 38));
        jLabel1.setText("Confirm Orders");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        receiptTA.setEditable(false);
        receiptTA.setColumns(20);
        receiptTA.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        receiptTA.setRows(5);
        receiptTA.setEnabled(false);
        jScrollPane1.setViewportView(receiptTA);
        receiptTA.setDisabledTextColor(new java.awt.Color(113, 96, 64));

        receiptTA.setText("   Product" + "\t\t" + "Size" + "\t" + "Quantity" + "\t" + "Price" + "\n");
        receiptTA.setText(receiptTA.getText() + "============================================================\n\n");

        for(int i = 0; i < bagContent.getRowCount(); i++){

            String productName = bagContent.getValueAt(i, 0).toString();
            String productSize = (productName.length() < 11) ? "\t" + bagContent.getValueAt(i, 1).toString(): bagContent.getValueAt(i, 1).toString();
            String quantity = bagContent.getValueAt(i, 2).toString();
            String price = "PHP " + String.valueOf(Menu.decimalFormat.format( Double.parseDouble(bagContent.getValueAt(i, 3).toString())));

            receiptTA.setText(receiptTA.getText() + "   " + productName + "\t" + productSize + "\t" + quantity + "\t" + price + "\n");
        }
        receiptTA.setText(receiptTA.getText() + "\n============================================================\n");
        receiptTA.setText(String.format(receiptTA.getText() + "   \t\t\t           Total: \tPHP %s\n", Menu.totalPriceInBag));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 8, 38));
        jLabel2.setText("Pay with:");

        gcashRB.setBackground(new java.awt.Color(249, 244, 239));
        paymentButtonGroup.add(gcashRB);
        gcashRB.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        gcashRB.setForeground(new java.awt.Color(2, 8, 38));
        gcashRB.setText("GCash");
        gcashRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcashRBActionPerformed(evt);
            }
        });

        cashRB.setBackground(new java.awt.Color(249, 244, 239));
        paymentButtonGroup.add(cashRB);
        cashRB.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cashRB.setForeground(new java.awt.Color(2, 8, 38));
        cashRB.setText("Cash");
        cashRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRBActionPerformed(evt);
            }
        });

        pickupRB.setBackground(new java.awt.Color(249, 244, 239));
        deliveryPickupGroup.add(pickupRB);
        pickupRB.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        pickupRB.setForeground(new java.awt.Color(2, 8, 38));
        pickupRB.setText("Pick-up");
        pickupRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupRBActionPerformed(evt);
            }
        });

        deliveryRB.setBackground(new java.awt.Color(249, 244, 239));
        deliveryPickupGroup.add(deliveryRB);
        deliveryRB.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        deliveryRB.setForeground(new java.awt.Color(2, 8, 38));
        deliveryRB.setText("Delivery");

        addressTextFLabel.setBackground(new java.awt.Color(249, 244, 239));
        addressTextFLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addressTextFLabel.setForeground(new java.awt.Color(2, 8, 38));
        addressTextFLabel.setText("Address:");

        addressTextField.setBackground(new java.awt.Color(230, 230, 230));
        addressTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addressTextField.setForeground(new java.awt.Color(71, 54, 47));
        addressTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 5, 2, 1));
        addressTextField.setPreferredSize(new java.awt.Dimension(110, 25));
        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(140, 120, 81));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 254));
        jButton1.setText("Confirm");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(pickupRB)
                                    .addGap(18, 18, 18)
                                    .addComponent(deliveryRB)))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cashRB)
                                .addGap(30, 30, 30)
                                .addComponent(gcashRB)))
                        .addGap(18, 18, 18)
                        .addComponent(addressTextFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashRB)
                    .addComponent(gcashRB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addressTextFLabel)
                        .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pickupRB)
                        .addComponent(deliveryRB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        gcashRB.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent e){
                if(!(methods.getSelectedButton(Payment.paymentButtonGroup) == null || methods.getSelectedButton(Payment.paymentButtonGroup).equals("Cash"))){
                    openQrFrame();
                }
            }
        });
        cashRB.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent e){
            }
        });
        pickupRB.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent e){
                addressTextFLabel.setVisible(false);
                addressTextField.setVisible(false);
            }
        });
        deliveryRB.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent e){
                addressTextFLabel.setVisible(true);
                addressTextField.setVisible(true);
            }
        });
        addressTextFLabel.setVisible(false);
        addressTextField.setBorder(border);
        addressTextField.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gcashRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcashRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gcashRBActionPerformed

    private void cashRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashRBActionPerformed

    private void pickupRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pickupRBActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(methods.getSelectedButton(deliveryPickupGroup).equals("Delivery") && addressTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please input your address");
        }
        else{
            if(!(methods.getSelectedButton(deliveryPickupGroup).equals("Delivery"))){
                addressTextField.setText(null);
            }
            
            DBQuery.insertTransactionToDatabase(Menu.totalPriceInBag, methods.getSelectedButton(paymentButtonGroup), methods.getSelectedButton(deliveryPickupGroup), addressTextField.getText());
            DBQuery.insertOrdersToDB();

            Menu.totalPriceInBag = 0;
            Menu.totalPriceLabel.setText("PHP " + Menu.decimalFormat.format(Menu.totalPriceInBag));

            methods.clearTable(Menu.bagContent.getModel());
            mainFrame.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Order confirmed\nThank you for purchasing in our shop");
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void openQrFrame(){
        if(methods.getSelectedButton(paymentButtonGroup).equals("GCash")){
            QrCode qrForm = new QrCode(this);
            qrForm.setVisible(true);
            qrForm.pack();
            qrForm.setLocationRelativeTo(null);
            
            this.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment(mainFrame).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressTextFLabel;
    public static javax.swing.JTextField addressTextField;
    private javax.swing.JRadioButton cashRB;
    public static javax.swing.ButtonGroup deliveryPickupGroup;
    private javax.swing.JRadioButton deliveryRB;
    private javax.swing.JRadioButton gcashRB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.ButtonGroup paymentButtonGroup;
    private javax.swing.JRadioButton pickupRB;
    private javax.swing.JTextArea receiptTA;
    // End of variables declaration//GEN-END:variables
}
