/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffeesystem;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author johnc
 */
public class ProductPage extends javax.swing.JFrame {

    /**
     * Creates new form ProductPage
     */
    public ProductPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ourMenuBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        orderListBtn = new javax.swing.JButton();
        userListBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        beveragesTable = new javax.swing.JTable();
        editProductBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 244, 239));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 800));

        jPanel3.setBackground(new java.awt.Color(232, 231, 230));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 720));

        logoutBtn.setBackground(new java.awt.Color(232, 231, 230));
        logoutBtn.setFont(new java.awt.Font("Leelawadee UI", 2, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(113, 96, 64));
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        logoutBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        profileBtn.setBackground(new java.awt.Color(230, 230, 230));
        profileBtn.setFont(new java.awt.Font("Leelawadee UI", 2, 18)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(113, 96, 64));
        profileBtn.setText("My Profile");
        profileBtn.setBorder(null);
        profileBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        profileBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        jSeparator1.setPreferredSize(new java.awt.Dimension(300, 10));

        ourMenuBtn.setBackground(new java.awt.Color(232, 231, 230));
        ourMenuBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ourMenuBtn.setForeground(new java.awt.Color(113, 96, 64));
        ourMenuBtn.setText("Our Menu");
        ourMenuBtn.setBorder(null);
        ourMenuBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ourMenuBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        ourMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourMenuBtnActionPerformed(evt);
            }
        });

        dashboardBtn.setBackground(new java.awt.Color(232, 231, 230));
        dashboardBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(113, 96, 64));
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setBorder(null);
        dashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        dashboardBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });

        productBtn.setBackground(new java.awt.Color(232, 231, 230));
        productBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        productBtn.setForeground(new java.awt.Color(113, 96, 64));
        productBtn.setText("Products");
        productBtn.setBorder(null);
        productBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        productBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });

        orderListBtn.setBackground(new java.awt.Color(230, 230, 230));
        orderListBtn.setFont(new java.awt.Font("Leelawadee UI", 3, 18)); // NOI18N
        orderListBtn.setForeground(new java.awt.Color(113, 96, 64));
        orderListBtn.setText("Orders");
        orderListBtn.setBorder(null);
        orderListBtn.setFocusable(false);
        orderListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        orderListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        orderListBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        orderListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderListBtnActionPerformed(evt);
            }
        });

        userListBtn.setBackground(new java.awt.Color(230, 230, 230));
        userListBtn.setFont(new java.awt.Font("Leelawadee UI", 3, 18)); // NOI18N
        userListBtn.setForeground(new java.awt.Color(113, 96, 64));
        userListBtn.setText("Users");
        userListBtn.setBorder(null);
        userListBtn.setFocusable(false);
        userListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        userListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        userListBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        userListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userListBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ourMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(ourMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(orderListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(userListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 8, 38));
        jLabel2.setText("Beverages Table");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        beveragesTable.setBackground(new java.awt.Color(240, 240, 240));
        beveragesTable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        beveragesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Beverage ID", "Beverages", "Size", "Category", "Price", "Availability"
            }
        ){
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        });
        beveragesTable.setRowHeight(25);
        jScrollPane2.setViewportView(beveragesTable);
        JTableHeader header = beveragesTable.getTableHeader();

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) beveragesTable.getDefaultRenderer(Object.class);
        renderer.setHorizontalAlignment( SwingConstants.CENTER );
        renderer.setVerticalAlignment( SwingConstants.CENTER );

        Dimension d = header.getPreferredSize();
        header.setPreferredSize(new Dimension(d.width, 30));
        header.setFont(new java.awt.Font("SansSerif", 1, 15));
        header.setBackground(new java.awt.Color(240,240,240));

        DBQuery.loadProducts();

        editProductBtn.setBackground(new java.awt.Color(140, 120, 81));
        editProductBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        editProductBtn.setForeground(new java.awt.Color(255, 255, 254));
        editProductBtn.setText("Edit Row");
        editProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(910, 910, 910))
                            .addComponent(jScrollPane2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(editProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int confirmLogout = JOptionPane.showConfirmDialog(null, "Do you want to logout?", "Log Out", JOptionPane.YES_NO_OPTION);

        if (confirmLogout == JOptionPane.YES_NO_OPTION){
            LogIn LogInFrame = new LogIn();
            LogInFrame.setVisible(true);
            LogInFrame.pack();
            LogInFrame.setLocationRelativeTo(null);

            this.dispose();
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        Account accountFrame = new Account();
        accountFrame.setVisible(true);
        accountFrame.pack();
        accountFrame.setLocationRelativeTo(null);
                
        Account.ourMenuBtn.setText("Dashboard");
        Account.productBtn.setText("Products");
        Account.orderListBtn.setVisible(true);
        Account.userListBtn.setVisible(true);
                
        this.dispose();
    }//GEN-LAST:event_profileBtnActionPerformed

    private void editProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductBtnActionPerformed
        // TODO add your handling code here:
        if(beveragesTable.getSelectedRowCount() != 0){
            int selectedRow = beveragesTable.getSelectedRow();

            Vector data = new Vector();
            data.add(beveragesTable.getValueAt(selectedRow, 0));
            data.add(beveragesTable.getValueAt(selectedRow, 1));
            data.add(beveragesTable.getValueAt(selectedRow, 2));
            data.add(beveragesTable.getValueAt(selectedRow, 3));
            data.add(beveragesTable.getValueAt(selectedRow, 4));
            data.add(beveragesTable.getValueAt(selectedRow, 5));
            
            EditProduct editProductFrame = new EditProduct( this,data);
            editProductFrame.setVisible(true);
            editProductFrame.pack();
            editProductFrame.setLocationRelativeTo(null);
            
            this.setEnabled(false);
        }
    }//GEN-LAST:event_editProductBtnActionPerformed

    private void ourMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ourMenuBtnActionPerformed
        // TODO add your handling code here:
        Menu menuFrame = new Menu();
        menuFrame.setVisible(true);
        menuFrame.pack();
        menuFrame.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_ourMenuBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        Dashboard dashboardFrame = new Dashboard();
        dashboardFrame.setVisible(true);
        dashboardFrame.pack();
        dashboardFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
        ProductPage productFrame = new ProductPage();
        productFrame.setVisible(true);
        productFrame.pack();
        productFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_productBtnActionPerformed

    private void orderListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderListBtnActionPerformed
        // TODO add your handling code here:
        OrderPage orderPageFrame = new OrderPage();
        orderPageFrame.setVisible(true);
        orderPageFrame.pack();
        orderPageFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_orderListBtnActionPerformed

    private void userListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userListBtnActionPerformed
        // TODO add your handling code here:
        UserPage userFrame = new UserPage();
        userFrame.setVisible(true);
        userFrame.pack();
        userFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_userListBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable beveragesTable;
    public static javax.swing.JButton dashboardBtn;
    private javax.swing.JButton editProductBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutBtn;
    public static javax.swing.JButton orderListBtn;
    public static javax.swing.JButton ourMenuBtn;
    public static javax.swing.JButton productBtn;
    private javax.swing.JButton profileBtn;
    public static javax.swing.JButton userListBtn;
    // End of variables declaration//GEN-END:variables
}
