/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffeesystem;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author johnc
 */
public class UserPage extends javax.swing.JFrame {
    
    JComboBox roleSelection;
    
    public UserPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ourMenuBtn1 = new javax.swing.JButton();
        ourMenuBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        orderListBtn = new javax.swing.JButton();
        userListBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        deleteUserBtn = new javax.swing.JButton();
        editRoleBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainFrame.setPreferredSize(new java.awt.Dimension(1500, 800));

        jPanel3.setBackground(new java.awt.Color(232, 231, 230));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 800));

        logoutBtn.setBackground(new java.awt.Color(232, 231, 230));
        logoutBtn.setFont(new java.awt.Font("Leelawadee UI", 2, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(113, 96, 64));
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        logoutBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        profileBtn.setBackground(new java.awt.Color(230, 230, 230));
        profileBtn.setFont(new java.awt.Font("Leelawadee UI", 2, 18)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(113, 96, 64));
        profileBtn.setText("My Profile");
        profileBtn.setBorder(null);
        profileBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        profileBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        jSeparator1.setPreferredSize(new java.awt.Dimension(300, 10));

        ourMenuBtn1.setBackground(new java.awt.Color(232, 231, 230));
        ourMenuBtn1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ourMenuBtn1.setForeground(new java.awt.Color(113, 96, 64));
        ourMenuBtn1.setText("Dashboard");
        ourMenuBtn1.setBorder(null);
        ourMenuBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ourMenuBtn1.setPreferredSize(new java.awt.Dimension(170, 40));
        ourMenuBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourMenuBtn1ActionPerformed(evt);
            }
        });

        ourMenuBtn.setBackground(new java.awt.Color(232, 231, 230));
        ourMenuBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ourMenuBtn.setForeground(new java.awt.Color(113, 96, 64));
        ourMenuBtn.setText("Our Menu");
        ourMenuBtn.setBorder(null);
        ourMenuBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ourMenuBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        ourMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourMenuBtnActionPerformed(evt);
            }
        });

        productBtn.setBackground(new java.awt.Color(232, 231, 230));
        productBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        productBtn.setForeground(new java.awt.Color(113, 96, 64));
        productBtn.setText("Products");
        productBtn.setBorder(null);
        productBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        productBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });

        orderListBtn.setBackground(new java.awt.Color(230, 230, 230));
        orderListBtn.setFont(new java.awt.Font("Leelawadee UI", 3, 18)); // NOI18N
        orderListBtn.setForeground(new java.awt.Color(113, 96, 64));
        orderListBtn.setText("Orders");
        orderListBtn.setBorder(null);
        orderListBtn.setFocusable(false);
        orderListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        orderListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        orderListBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        orderListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderListBtnActionPerformed(evt);
            }
        });

        userListBtn.setBackground(new java.awt.Color(230, 230, 230));
        userListBtn.setFont(new java.awt.Font("Leelawadee UI", 3, 18)); // NOI18N
        userListBtn.setForeground(new java.awt.Color(113, 96, 64));
        userListBtn.setText("Users");
        userListBtn.setBorder(null);
        userListBtn.setFocusable(false);
        userListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        userListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        userListBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        userListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userListBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ourMenuBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ourMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(ourMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(ourMenuBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(orderListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(userListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(249, 244, 239));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        userTable.setBackground(new java.awt.Color(240, 240, 240));
        userTable.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name", "Email", "Contact", "Gender", "Role", "Last Login"
            }
        ){
            public boolean isCellEditable(int rowIndex, int columnIndex){
                if(columnIndex == 5){
                    return true;
                }
                return false;
            }
        });
        userTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        userTable.setRowHeight(30);
        userTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(userTable);
        JTableHeader header = userTable.getTableHeader();

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) userTable.getDefaultRenderer(Object.class);
        renderer.setHorizontalAlignment( SwingConstants.CENTER );
        renderer.setVerticalAlignment( SwingConstants.CENTER );

        Dimension d = header.getPreferredSize();
        header.setPreferredSize(new Dimension(d.width, 30));
        header.setFont(new java.awt.Font("SansSerif", 1, 15));
        header.setBackground(new java.awt.Color(240,240,240));

        userTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        userTable.getColumnModel().getColumn(1).setPreferredWidth(180);
        userTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        userTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        userTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        userTable.getColumnModel().getColumn(5).setPreferredWidth(50);

        TableColumn roleColumn = userTable.getColumnModel().getColumn(5);
        roleSelection = new JComboBox();

        roleSelection.addItem("employee");
        roleSelection.addItem("admin");
        roleColumn.setCellEditor(new DefaultCellEditor(roleSelection));

        DBQuery.loadUsers();

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 8, 38));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-icon.png"))); // NOI18N
        jLabel2.setText("User Table");

        deleteUserBtn.setBackground(new java.awt.Color(140, 120, 81));
        deleteUserBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        deleteUserBtn.setForeground(new java.awt.Color(255, 255, 254));
        deleteUserBtn.setText("Delete User");
        deleteUserBtn.setPreferredSize(new java.awt.Dimension(150, 40));
        deleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtnActionPerformed(evt);
            }
        });

        editRoleBtn.setBackground(new java.awt.Color(140, 120, 81));
        editRoleBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        editRoleBtn.setForeground(new java.awt.Color(255, 255, 254));
        editRoleBtn.setText("Edit Role");
        editRoleBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        editRoleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRoleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addContainerGap(963, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(editRoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(deleteUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editRoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE))
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int confirmLogout = JOptionPane.showConfirmDialog(null, "Do you want to logout?", "Log Out", JOptionPane.YES_NO_OPTION);

        if (confirmLogout == JOptionPane.YES_NO_OPTION){
            LogIn LogInFrame = new LogIn();
            LogInFrame.setVisible(true);
            LogInFrame.pack();
            LogInFrame.setLocationRelativeTo(null);

            this.dispose();
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        Account accountFrame = new Account();
        accountFrame.setVisible(true);
        accountFrame.pack();
        accountFrame.setLocationRelativeTo(null);

        Account.ourMenuBtn.setText("Dashboard");
        Account.productBtn.setText("Products");
        Account.orderListBtn.setVisible(true);
        Account.userListBtn.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_profileBtnActionPerformed

    private void deleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBtnActionPerformed
        // TODO add your handling code here:
        if(!DBQuery.getUserRole(CoffeeSystem.userEmail).equals("admin")){
            JOptionPane.showMessageDialog(null, "Only admin can change user role");
        }
        else{
            if(userTable.getSelectedRowCount() != 0){
                String lastLoginStr = userTable.getValueAt(userTable.getSelectedRow(), 6).toString();
                int userID = (int) userTable.getValueAt(userTable.getSelectedRow(), 0);
                DateTimeFormatter ymdFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
                LocalDateTime lastLogin = LocalDateTime.parse(lastLoginStr, ymdFormat);

                if(userTable.getValueAt(userTable.getSelectedRow(), 6).equals("admin")){
                    JOptionPane.showMessageDialog(null, "User is an admin\nUser cannot be deleted");
                }
                else{
                    if(lastLogin.isBefore(LocalDateTime.now().minusYears(1))){
                        int confirmUserDeletion = JOptionPane.showConfirmDialog(null, "User has not log in for more than a year", "Delete user", JOptionPane.YES_NO_OPTION);
                        if(confirmUserDeletion == JOptionPane.YES_OPTION){
                            if(DBQuery.isOrderOfUserEmpty(userID)){
                                DBQuery.clearUserOrder(userID);
                                DBQuery.clearUserTransaction(userID);
                            }
                            DBQuery.deleteUser(userID);

                            methods.clearTable(userTable.getModel());
                            DBQuery.loadUsers();
                        }
                    }
                    else{
                        int confirmUserDeletion = JOptionPane.showConfirmDialog(null, "User just log in last " + lastLoginStr.substring(0, 10), "Delete user", JOptionPane.YES_NO_OPTION);
                        if(confirmUserDeletion == JOptionPane.YES_OPTION){
                            if(DBQuery.isOrderOfUserEmpty(userID)){
                                DBQuery.clearUserOrder(userID);
                                DBQuery.clearUserTransaction(userID);
                            }
                            DBQuery.deleteUser(userID);

                            methods.clearTable(userTable.getModel());
                            DBQuery.loadUsers();
                        }
                    }
                } 
            }
        }
    }//GEN-LAST:event_deleteUserBtnActionPerformed

    private void editRoleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRoleBtnActionPerformed
        // TODO add your handling code here:
        if(!DBQuery.getUserRole(CoffeeSystem.userEmail).equals("admin")){
            JOptionPane.showMessageDialog(null, "Only admin can change user role");
        }
        else{
            if(userTable.getSelectedRowCount() != 0){
                String selectedUserRole = DBQuery.getUserRole(userTable.getValueAt(userTable.getSelectedRow(), 2).toString());
                String newRole = roleSelection.getSelectedItem().toString();

                if(selectedUserRole.equals("customer") && newRole.equals("admin")){
                    int confirmChangeRole = JOptionPane.showConfirmDialog(null, "This user has a customer role\nGiving him an admin role will give him full access to our system\nDo you want to continue?", "Give admin access", JOptionPane.YES_NO_OPTION);
                    if(confirmChangeRole == JOptionPane.YES_OPTION){
                        DBQuery.changeUserRole((int) userTable.getValueAt(userTable.getSelectedRow(), 0), newRole);
                    }
                }
                else{
                    int confirmChangeRole = JOptionPane.showConfirmDialog(null, "Changing user role\nDo you want to continue?", "Confirm role change", JOptionPane.YES_NO_OPTION);
                    if(confirmChangeRole == JOptionPane.YES_OPTION){
                        DBQuery.changeUserRole((int) userTable.getValueAt(userTable.getSelectedRow(), 0), newRole);
                    }
                }
            }
        }
    }//GEN-LAST:event_editRoleBtnActionPerformed

    private void ourMenuBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ourMenuBtn1ActionPerformed
        // TODO add your handling code here:
        Menu menuFrame = new Menu();
        menuFrame.setVisible(true);
        menuFrame.pack();
        menuFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_ourMenuBtn1ActionPerformed

    private void ourMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ourMenuBtnActionPerformed
        // TODO add your handling code here:
        Menu menuFrame = new Menu();
        menuFrame.setVisible(true);
        menuFrame.pack();
        menuFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_ourMenuBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
        ProductPage productFrame = new ProductPage();
        productFrame.setVisible(true);
        productFrame.pack();
        productFrame.setLocationRelativeTo(null);

        this.dispose();

    }//GEN-LAST:event_productBtnActionPerformed

    private void orderListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderListBtnActionPerformed
        // TODO add your handling code here:
        OrderPage orderPageFrame = new OrderPage();
        orderPageFrame.setVisible(true);
        orderPageFrame.pack();
        orderPageFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_orderListBtnActionPerformed

    private void userListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userListBtnActionPerformed
        // TODO add your handling code here:
        UserPage userFrame = new UserPage();
        userFrame.setVisible(true);
        userFrame.pack();
        userFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_userListBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteUserBtn;
    private javax.swing.JButton editRoleBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainFrame;
    public static javax.swing.JButton orderListBtn;
    public static javax.swing.JButton ourMenuBtn;
    public static javax.swing.JButton ourMenuBtn1;
    public static javax.swing.JButton productBtn;
    private javax.swing.JButton profileBtn;
    public static javax.swing.JButton userListBtn;
    public static javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
